[package]
name = "program"
version = "0.1.0"
edition = "2024"

[dependencies]
anchor-lang = { path = "../anchor/lang", features = [
    "derive",
    "event-cpi",
    "interface-instructions",
    "idl-build",
    "anchor-debug",
    "init-if-needed",
    "allow-missing-optionals",
] }